### ISSUE TITLE
Search support

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/docs.ubuntu.com#11]
Ability to search through documentation.

### Styling requirements

- Search should be in top right of main nav bar
- Search results display in content area

**Comment by pmatulis** [comment]
Requirements:

- [ ] Make it very clear to the user they are searching within a specific software version
- [ ] Allow a user to choose multiple technologies

**Comment by evilnick** [comment]
search should:

 * initially restrict results to version of docs user is coming from
 * Be capable of broader serch (e.g. all versions, possibly all documentation)
 * Be very obvious about where specifically results are coming from

**Comment by degville** [comment]
though not an immediate requirement, we may need to publish languages/translations other than English (eg. zh/2.0/getting-started).

**Comment by evilnick** [comment]
Yes, though that would be /2.0/zh/squiggles

**Comment by nottrobin** [comment]
We have implemented search - e.g.: <https://docs.ubuntu.com/search?q=ubuntu&domain=docs.ubuntu.com/maas>

I don't think it has quite all the features mentioned here, but since the basic feature is implemented I'm going to close this. Please feel free to open another issue about search improvements if you think it's missing anything important.
