### ISSUE TITLE
Product docs are separated with no standard doc types per product

### ISSUE THREAD

**Issue by knitzsche** [canonical-websites/docs.ubuntu.com#114]
## Summary

docs.ubuntu.com provides links to various product docs: ubuntu-core, MAAS, Landscape, Phone (really?), etc. 

Clicking a "Documentation" link opens the product's docs as the top level page. This has several problems:

* Canonical products are presented as separate entities (they do share a visual theme), not as a set of integrated products by one company unified by a compelling vision.

* It's an obstacle for users finding other product docs (they have to open docs.ubuntu.com again manually). For example, how do they get from ubuntu-core docs back to the docs.ubuntu.com home page?

* A related point is that each product's docs get only a free-form, left-side nav bar, so there is no common (enforceable) understanding of standard types of docs for every product. I would expect to see (for each product) at least guide(s) and tutorials, and also in many cases reference, and possibly others. See [1] for an example of what I think we should aim for.

## Proposal

A suggestion to fix this would be that docs.ubuntu.com has a top level nav like this:
Product | Guides | Turorials | Reference |...

Selecting the Product (ubuntu-core, MAAS, etc) displays that product (and updates the remaining right side nav bar items accordingly). 

* No navigating away to what feels like another site and finding your way back

* Present a standard set of doc types for a given product across the top that feels designed and intentional and is consistent with doc types in the industry

[1] https://docs.particle.io/guide/getting-started/intro/photon/

**Comment by tbille** [comment]
A lot changed since. We are redesigning for the structure of documentations.
I am closing this issue for now.
