### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by degville** [canonical-websites/docs.ubuntu.com#118]
## Summary

Search across various docs.ubuntu.com docs sites appears broken, returning 
`Failed to retrieve search results (connection error).` instead of results.

## Process

- Go to https://docs.ubuntu.com/maas/2.1/en/
- Enter test into the 'Search' field
- Wait indefinitely

## Current and expected result

Returned result is `Failed to retrieve search results (connection error).` after a wait.
The results should be returned.

## Screenshot

![image](https://user-images.githubusercontent.com/7047542/31449294-6d9300dc-ae9e-11e7-8237-2cdb59ca816a.png)

**Comment by anthonydillon** [comment]
Thanks @degville

**Comment by nottrobin** [comment]
Fixed!
