### ISSUE TITLE
Search returns Connection Errors, fails to return any results

### ISSUE THREAD

**Issue by bladernr** [canonical-websites/docs.ubuntu.com#119]
## Summary

Trying to search MAAS docs for info on iSCSI. Instead of getting resutls , or a no-results-found, I get a connection error and this message:

Failed to retrieve search results (connection error). If you have time, please file a bug.

## Process

Go to https://docs.ubuntu.com/maas/devel/en/
In the search box, type 'iSCSI' and hit return or click the icon.
Page will churn for a bit before eventually timing out with the above mentioned error message:
This is the  URL we land on:
https://docs.ubuntu.com/search?q=iSCSI&domain=docs.ubuntu.com%2Fmaas
This is the message we get:
Failed to retrieve search results (connection error). If you have time, please file a bug.

I also tried searching for 'DNS', 'ISO', and a handful of other MAAS relevant search terms and got the timeout ever time.

## Current and expected result

Result: Connection Error and no search results.
Expected Result: Return links to documentation that are apropos to the search term 'iSCSI'

## Screenshot

![maas-doc-search-fail](https://user-images.githubusercontent.com/4295496/31678522-6bbc686e-b33c-11e7-9096-53b184b2a6e8.png)

**Comment by nottrobin** [comment]
@bladernr thanks so much for bringing that to our attention. It's now fixed!

**Comment by nottrobin** [comment]
(the same as #118)
