### ISSUE TITLE
Support for multiple hostnames

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/docs.ubuntu.com#13]
We need the ability for this application to understand and serve several domains. E.g.:

- docs.vanillaframework.io
- docs.snapcraft.io
etc.

So the app needs updating to read a config file which will map hostnames to set of documentation. E.g.:

``` yaml
docs.vanillaframework.io: templates/vanillaframework/
docs.snapcraft.io: templates/snapcraft/
```

It should also then redirect from `docs.ubuntu.com/{product}` to `docs.{product}.io` in these cases.

This is important specifically for Vanillaframework and Snapcraft, because neither can host their documentation on this platform, as they should, until this is implemented.

**Comment by yaili** [comment]
@anthonydillon @nottrobin do we need to prioritise this issue?

**Comment by nottrobin** [comment]
Yes we should. I'll ask @frankiegranato to add it to the web squad backlog.

**Comment by nottrobin** [comment]
This will be fixed through https://github.com/canonical-websites/docs.ubuntu.com/issues/86
