### ISSUE TITLE
Mis-counted search results 

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/docs.ubuntu.com#136]
## Summary

When searching the docs, in particular MAAS docs, the results page miscounts the number of hits.

## Process

1. Visit https://docs.ubuntu.com/maas/2.3/en/
2. In the search box (top right) search for e.g. "foo"
3. Look at the [results page](https://docs.ubuntu.com/search?q=foo&domain=docs.ubuntu.com%2Fmaas)

## Current and expected result

![Current result](https://user-images.githubusercontent.com/246192/35804657-996e8dd8-0a70-11e8-8baa-fa485ffa4e71.png) shows 0 hits, and seems to be missing the "from" and "to" values where it says "Results to"

I expect it to say 2 hits and something like "Results 1 to 2"

**Comment by sparkiegeek** [comment]
See also https://github.com/canonical-websites/www.ubuntu.com/issues/2628

**Comment by tbille** [comment]
Not valid anymore with new search system
