### ISSUE TITLE
redirects for MAAS not working as expected

### ISSUE THREAD

**Issue by evilnick** [canonical-websites/docs.ubuntu.com#145]
## Summary

some maas url redirects not working as intended

## Current and expected result

docs.ubuntu.com/maas redirects to docs.maas.io/2.3/en/
docs.ubuntu.com/maas/ gives a 404

Both should redirect to  docs.maas.io/2.3/en/

There seem to be some external properties (e.g. wikipedia, being corrected) which refer to the latter

**Comment by tbille** [comment]
this seems to be fixed now
