### ISSUE TITLE
Searching juju docs is empty

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/docs.ubuntu.com#151]
If you go to docs.jujucharms.com and search for something like "cloud" there is no results. The pages should be indexed.

**Comment by nottrobin** [comment]
Filed an RT: [#110554: Please include docs.jujucharms.com in the Google Search Appliance index](https://portal.admin.canonical.com/C110554/)

**Comment by anthonydillon** [comment]
This has been complete and confirmed.

**Comment by nottrobin** [comment]
Fixed
