### ISSUE TITLE
docs.ubuntu.com “Report a bug” link goes to www.ubuntu.com repo

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/docs.ubuntu.com#157]
1\. On [docs.ubuntu.com](https://docs.ubuntu.com/), click “Report a bug on this site”.

What happens: You end up at [github.com/canonical-websites/www.ubuntu.com/issues/new](https://github.com/canonical-websites/www.ubuntu.com/issues/new)

What should happen: You end up at [github.com/canonical-websites/docs.ubuntu.com/issues](https://github.com/canonical-websites/docs.ubuntu.com/issues)

**Comment by tbille** [comment]
This has been fixed
