### ISSUE TITLE
“Search Style Guide docs” is misleading

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/docs.ubuntu.com#159]
1\. Go to [the Canonical Documentation Style Guide page](https://docs.ubuntu.com/styleguide/en).
2\. In the “Search Style Guide docs” field, enter anything that you know is present in the guide, for example “[hyperlinks](https://docs.ubuntu.com/search?q=hyperlinks&domain=docs.ubuntu.com%2Fstyleguide)” or “[headlines](https://docs.ubuntu.com/search?q=headlines&domain=docs.ubuntu.com%2Fstyleguide)”.

What happens:
> # Your search for 'headlines' returned 0 results
> 
> [ Search all docs ]
>
> ## 0 results for "headlines"
>
> Results to
>
> [| Style Guide](https://docs.ubuntu.com/styleguide/en)
>
> `https://docs.ubuntu.com/styleguide/en`

What’s wrong with this:
- It twice claims not to have any results.
- Nevertheless, it always returns exactly 1 result.
- It’s always the same result, which is the entire style guide.

What should happen: either
- the Style Guide doesn’t have a search field, since it’s only one page, so you can use your browser’s Find function instead, or
- the Style Guide is split into multiple pages, and the search accurately counts search results.

**Comment by tbille** [comment]
Not valid anymore with new way of handling search

**Comment by matthewpaulthomas** [comment]
The “0 results” statements are fixed. Unfortunately it’s still a problem that the search field implies that it will help you find things in the style guide, and doesn’t. Reported that as #213.
