### ISSUE TITLE
conjure-up link is invalid

### ISSUE THREAD

**Issue by battlemidget** [canonical-websites/docs.ubuntu.com#163]
## Summary

The conjure-up link is pointing to an old and missing page

## Process

docs.ubuntu.com, click on conjure-up

## Current and expected result

page not found, should point to latest docs

https://docs.conjure-up.io/stable/en/

The url has been updated to always reflect the stable documentation and alleviate the need to point to a versioned doc.

**Comment by anthonydillon** [comment]
This has been done and is live.
