### ISSUE TITLE
UX questions with regards to documentation platform background and strategy

### ISSUE THREAD

**Issue by MonicaSG** [canonical-websites/docs.ubuntu.com#17]
- What parts of the Canonical/Ubuntu ecosystem are/will be talking to the documentation platform?
- Who are the different users across those touchpoints?
- What are their user journeys?
- What is the purpose of the documentation platform for that journey?
- What content will they be accessing, and what format will that be in?

**Comment by nottrobin** [comment]
These questions are now stale - the world has changed shape considerably since then. Hopefully questions that are still important to be answered will re-emerge.
