### ISSUE TITLE
Landscape On Premises versions are outdated

### ISSUE THREAD

**Issue by davecore82** [canonical-websites/docs.ubuntu.com#171]
## Summary

The versions of Landscape On Premises are outdated on the page https://docs.ubuntu.com/landscape/en/onprem-overview

Specifically, as of today the page is missing versions 17.03 and 18.03

## Process

Visit https://docs.ubuntu.com/landscape/en/onprem-overview and compare it to https://help.landscape.canonical.com/

## Current and expected result

We should have the same versions as the list in https://help.landscape.canonical.com/ (missing 17.03 and 18.03)

**Comment by BryanQuigley** [comment]
Relaunched now on https://docs.ubuntu.com/landscape/en/onprem

This is also some oddly the wrong repo for bug reports.   

This can be closed.
