### ISSUE TITLE
rebuild-docs no documented and broken

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/docs.ubuntu.com#20]
### Issue
If you check out the project and `./run` you have no content; I was told to run `./rebuild-docs` to get some content.

This seems to rely on git-extras so I installed git-extras. Unfortunately the released version of git-extras doesn't yet include `git-force-clone`.

Perhaps consider using a slightly more verbose plain-vanilla git solution to this.

**Comment by nottrobin** [comment]
`rebuild-docs` is no longer a thing
