### ISSUE TITLE
URLs without language (/en/) should redirect to the correct language

### ISSUE THREAD

**Issue by pmatulis** [canonical-websites/docs.ubuntu.com#40]
For instance, with MAAS, this should work:

https://docs.ubuntu.com/maas/2.1/intro-concepts

instead of having to use

https://docs.ubuntu.com/maas/2.1/en/intro-concepts

**Comment by nottrobin** [comment]
Updated the title. This is a redirects issue.

**Comment by nottrobin** [comment]
Closing this as it's now encapsulated in #89
