### ISSUE TITLE
Redirect to latest version automatically

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/docs.ubuntu.com#45]
Currently redirects are setup manually to redirect e.g. `/maas` to `/maas/2.1/en/`.

This should happen automatically - I propose it should always redirect to the top item in the [`versions` file](https://github.com/CanonicalLtd/maas-docs/blob/master/versions).

There may be a related task to add functionality in documentation-builder / vanilla-docs-theme to notify the user if they're not viewing the latest version of the documentation.

**Comment by pmatulis** [comment]
This should redirect to the latest stable release. The Doc team will need to adjust this file accordingly. We definitely do not want to have 'devel' as the default.

**Comment by evilnick** [comment]
bump :smiley:

**Comment by nottrobin** [comment]
We are now going to keep the infrastructure for building & serving each documentation set in the documentation repositories themselves.

This infrastructure should therefore be built so that it automatically takes care of this redirection, as well as #79, #67 and #40.

**Comment by nottrobin** [comment]
Closing this as it's now encapsulated in #89
