### ISSUE TITLE
MAAS docs web redirects

### ISSUE THREAD

**Issue by pmatulis** [canonical-websites/docs.ubuntu.com#49]
Please add the following web redirects for the MAAS documentation. Thank you!

===

https://docs.ubuntu.com/maas/2.1/en/installconfig-server-iso >>>
https://docs.ubuntu.com/maas/2.1/en/installconfig-iso-install

https://docs.ubuntu.com/maas/2.1/en/installconfig-gui >>>
https://docs.ubuntu.com/maas/2.1/en/installconfig-webui

https://docs.ubuntu.com/maas/2.1/en/installconfig-deploy-nodes >>>
https://docs.ubuntu.com/maas/2.1/en/installconfig-nodes-deploy

https://docs.ubuntu.com/maas/2.1/en/installconfig-kernel >>>
https://docs.ubuntu.com/maas/2.1/en/installconfig-nodes-kernel-boot-options

https://docs.ubuntu.com/maas/2.1/en/installconfig-hwe-kernels >>>
https://docs.ubuntu.com/maas/2.1/en/installconfig-nodes-ubuntu-kernels

**Comment by pmatulis** [comment]
@nottrobin These are important links. Can this get done soon?

**Comment by pmahnke** [comment]
@pmatulis 

@nottrobin is on holiday from last week... perhaps @WillMoggridge can help?

**Comment by WillMoggridge** [comment]
Sure, I will get those done shortly

**Comment by pmatulis** [comment]
This is done. Closing.
