### ISSUE TITLE
[Firefox] Search bar - Magnifying glass is outside of the search bar 

### ISSUE THREAD

**Issue by joanasa89** [canonical-websites/docs.ubuntu.com#50]
Can you please fix search bar on desktop,medium and small screens.
![screen shot 2017-03-10 at 10 15 46](https://cloud.githubusercontent.com/assets/21334617/23791465/fd4cf2fa-057a-11e7-8a5d-8b703ca7b596.png)

**Comment by nottrobin** [comment]
Can't reproduce.
