### ISSUE TITLE
Deploy docs.ubuntu.com on K8s

### ISSUE THREAD

**Issue by pmatulis** [canonical-websites/docs.ubuntu.com#74]
I know this issue is being addressed via multiple issues but the Doc team needs a single issue for tracking purposes. It would be great if the aforementioned issues could be cited here.

I will cite the issues that are submitted whenever a publication problem is encountered:

#68 
#71 
#73 
#75

**Comment by nottrobin** [comment]
Please submit future issues as comments on this issue, rather than new issues. They all represent the same problem, which we are working to fix.

**Comment by nottrobin** [comment]
I won't close this yet, but it should be fundamentally fixed by #86, which should make the publishing process trivial by comparison.

**Comment by anthonydillon** [comment]
This is being tracked in #86. Closing here.
