### ISSUE TITLE
Could not build docs

### ISSUE THREAD

**Issue by pmatulis** [canonical-websites/docs.ubuntu.com#75]
https://jenkins.canonical.com/webteam/job/docs.ubuntu.com-deploy-to-staging/123/console

**Comment by nottrobin** [comment]
@pmatulis please be careful when posting full logs from our deployment systems in a public forum - they could easily be exposing some sensitive information. I don't *think* the one above had anything sensitive, but it's hard to be sure. I've removed it.

I'm also going to close #68, #71 and #73 as duplicates. If you have extra information about this problem please add it as a comment to this issue.

**Comment by nottrobin** [comment]
Ah I see #74 is actually the parent issue. I'll close this one too.
