### ISSUE TITLE
Nothing linked on https://docs.ubuntu.com/core/en/guides works

### ISSUE THREAD

**Issue by jamiedbennett** [canonical-websites/docs.ubuntu.com#78]
Navigating to https://docs.ubuntu.com/core/en/guides and clicking any of the links on the left hand navigation results in a 404.

**Comment by caldav** [comment]
@nottrobin I believe this is related to the issue I mentioned the other day. Where pages such as https://docs.ubuntu.com/core/en/guides/index.html are available at:
* https://docs.ubuntu.com/core/en/guides/index.html
* https://docs.ubuntu.com/core/en/guides/index
* https://docs.ubuntu.com/core/en/guides

But the latter breaks the navigation, for example:

https://docs.ubuntu.com/core/en/guides/build-device/image-building in the nav becomes https://docs.ubuntu.com/core/en/build-device/image-building

**Comment by nottrobin** [comment]
Yes I believe it is. The immediate fix is to not ever link to https://docs.ubuntu.com/core/en/guides but instead link to https://docs.ubuntu.com/core/en/guides/index. This will make sure all links on that page work as expected.

Of course the long-term fix is to process redirects properly. I thought we had an issue tracking this, but I don't see it now. I'll create it.

**Comment by nottrobin** [comment]
Covered by initially #79 and now #89. Closing this.
